import { u_pageHide } from '@/common/utils'
export default {
    // 状态
    "deviceInformation": (c) => true,
    "wanInformation": (c) => true,
    "dhcpInformation": (c) => true,
    "wifi24GInformation": (c) => true,
    "wifi5GInformation": (c) => true,
    "detectionInformation": (c) => c.account_level == "1",
    // 网络配置
    "networkSetting": (c) => true,
    "apnSetting": (c) => c.network_mode != '2',
    "simFuction": (c) => c.network_mode != '2',
    "esimManage": (c) => !c.HIDE_5G && c.network_mode != '2' && ((c.account_level == "1") || (c.current_card_type == "1" && c.esim_show == "1")),
    "displaySolution": (c) => !c.HIDE_5G && c.network_mode != '2' && u_pageHide(18),
    "sliceConfiguration": (c) => !c.HIDE_5G && c.network_mode != '2' && c.account_level != "3",
    "cellHandoverpenalty": (c) => !c.HIDE_5G && c.network_mode != '2' && c.account_level == "1",
    "ueConfiguration": (c) => !c.HIDE_5G && c.network_mode != '2' && u_pageHide(79),
    "trafficSetting": (c) => !c.HIDE_5G && u_pageHide(94, true),
    "networkMode": (c) => u_pageHide(84, true) && c.network_mode != '2',
    "networkConfiguration": (c) => c.network_mode != '2',
    "plmnScan": (c) => u_pageHide(44) && c.network_mode != '2',
    "wanMode": (c) => u_pageHide(52) && (!c.HIDE_5G || c.account_level == "1"),
    "linkdetection": (c) => u_pageHide(93, true) && !c.HIDE_5G,
    "mainApn": (c) => true,
    "multipleApnSettings": (c) =>  u_pageHide(52),
    "pinCode": (c) => true,
    "simSwitch": (c) => c.esim_show == "1" || u_pageHide(17),
    "ueCapabilityConfig": (c) => true,
    "otherConfiguration": (c) => true,
    // WIFI
    "wifi24GSettings": (c) => true,
    "wifi24GAdvanceSettings": (c) => true,
    "wifi5GSettings": (c) => true,
    "wifi5GAdvanceSettings": (c) => true,
    "wpsSettings": (c) => true,
    "wifiBlackOrWhiteList": (c) => u_pageHide(56),
    "nfc": (c) => u_pageHide(125) && !c.HIDE_5G,
    "mainWifiSettings": (c) => true,
    "WifiSettings1": (c) => u_pageHide(19),
    "WifiSettings2": (c) => u_pageHide(20),
    "WifiSettings3": (c) => u_pageHide(21),
    "WifiSettings4": (c) => u_pageHide(22),
    "mainWifiSettings_5G": (c) => true,
    "WifiSettings1_5G": (c) => u_pageHide(23),
    "WifiSettings2_5G": (c) => u_pageHide(24),
    "WifiSettings3_5G": (c) => u_pageHide(25),
    "WifiSettings4_5G": (c) => u_pageHide(26),
    "advanceSettings": (c) => true,
    "ptc": (c) => c.account_level == '1',
    "wpsSettings24G": (c) => true,
    "wpsSettings5G": (c) => true,
    "blackWhiteList24G": (c) => true,
    "blackWhiteList5G": (c) => true,
    // 设备配置
    "dhcpSettings": (c) => c.network_mode != "7",
    "valnSettings": (c) => u_pageHide(116),
    "routeSettings": (c) => u_pageHide(68, true),
    "warmControl": (c) => u_pageHide(124) && !c.HIDE_5G,
    "vpn": (c) => u_pageHide(31),
    "voiceSettings": (c) => u_pageHide(100),
    "tr069": (c) => u_pageHide(41) || c.account_level != "3",
    "autoSleepSettings": (c) => c.account_level == "1" && !c.HIDE_5G,
    "snmp": (c) => u_pageHide(120) && !c.HIDE_5G,
    "exchangePlatform": (c) => (u_pageHide(32)||u_pageHide(53)||u_pageHide(54)||u_pageHide(96)||u_pageHide(108)) && !c.HIDE_5G,
    "ipPassthrough": (c) => u_pageHide(29),
    "advancedSettings": (c) => u_pageHide(49) && c.network_mode != "2",
    "simUnlock": (c) => u_pageHide(97),
    "mesh": (c) => u_pageHide(95),
    "antennaControl": (c) => u_pageHide(142),
    "mainDhcpSetting": (c) => true,
    "multipleDhcpSetting": (c) => u_pageHide(137),
    "staticRoutingTable": (c) => true,
    "ARPAgingTime": (c) => u_pageHide(30),
    "vpnSettings": (c) => u_pageHide(31),
    "greSettings": (c) => u_pageHide(45),
    "l2tpv3Settings": (c) => u_pageHide(57),
    "vxlanSettings": (c) => u_pageHide(83),
    "ipsecVpn": (c) => u_pageHide(55),
    "ipsecStatus": (c) => u_pageHide(55),
    "voiceBasicSettings": (c) => u_pageHide(100),
    "voiceAdvancedSettings": (c) => u_pageHide(99),
    "voipAdvancedSettings": (c) => u_pageHide(102),
    "specialKeyCodeSettings": (c) => u_pageHide(103),
    "oneNet": (c) => u_pageHide(32),
    "mobileDM": (c) => u_pageHide(53),
    "telecomDM": (c) => u_pageHide(54),
    "unicomDMP": (c) => u_pageHide(96),
    "mqttSettings": (c) => u_pageHide(108),
    "ddns": (c) => u_pageHide(33),
    "remoteLogin": (c) => u_pageHide(34),
    "lockPlmn": (c) => u_pageHide(35) && c.network_mode != '2',
    "frequencyBand": (c) => u_pageHide(36) && c.network_mode != '2',
    "localPhysicalCellLocking": (c) => u_pageHide(37) && c.network_mode != '2',
    "pciLock": (c) => u_pageHide(98),
    "basicSettings": (c) => u_pageHide(193),
    "meshAdvSetting": (c) => u_pageHide(194),
    "meshAction": (c) => u_pageHide(195),
    "networkingTopology": (c) => u_pageHide(196),
    // 短信
    "SMS": (c) => u_pageHide(107) && c.sim_status=='1',
    "inbox": (c) => u_pageHide(107) && c.smsSw == "1",
    "outbox": (c) => u_pageHide(107) && c.smsSw == "1",
    "smsSettings": (c) => u_pageHide(107),
    // 防火墙
    "firewall": (c) => c.network_mode != "2" && c.network_mode != "7",
    "dmz": (c) => c.network_mode != "2" && u_pageHide(61, true),
    "portForwarding": (c) => c.network_mode != "2",
    "filteringRules": (c) => c.network_mode != "2" && u_pageHide(62, true),
    "urlFilter": (c) => c.network_mode != "2" && u_pageHide(63, true),
    "ipMacBinding": (c) => c.network_mode != "2" && u_pageHide(64, true),
    "staticARPBinding": (c) => c.network_mode != "2" && u_pageHide(65, true),
    "ddosProtection": (c) => c.network_mode != "2" && u_pageHide(67, true),
    "speedLimit": (c) => c.network_mode != "2" && u_pageHide(38),
    "upnp": (c) => c.network_mode != "2" && u_pageHide(39),
    "remoteWebSettings": (c) => c.network_mode != "2" && u_pageHide(85, true),
    "accessControl": (c) => c.network_mode != "2" && u_pageHide(118, true),  
    // 家长控制
    "parentControl": (c) => !c.HIDE_5G && u_pageHide(153),
    "parent": (c) => !c.HIDE_5G && u_pageHide(153),
    "urlLimit": (c) => !c.HIDE_5G && u_pageHide(153) && c.parentControlSwitch == "1",
    "timeLimit": (c) => !c.HIDE_5G && u_pageHide(153) && c.parentControlSwitch == "1",
    "limitSpeed": (c) => !c.HIDE_5G && u_pageHide(153) && c.parentControlSwitch == "1",
    // 系统设置
    "systemSettings": (c) => true,
    "smartSettings": (c) => u_pageHide(143),
    "systemLog": (c) => u_pageHide(70, true),
    "exportLog": (c) => u_pageHide(71, true),
    "lOGInformation": (c) => c.account_level != "3",
    "systemUpgrade": (c) => u_pageHide(72, true),
    "systemAutoUpgrade": (c) => u_pageHide(40),
    "configUpgrade": (c) => c.account_level == "1" && c.build_type == "debug",
    "atCommand": (c) => c.account_level == "1",
    "networkTools": (c) => u_pageHide(73, true),
    "help": (c) => true,
    "sysSet": (c) => true,
    "changePassword": (c) => true,
    "changeUsername": (c) => c.account_level != "3",
    "timeSettings": (c) => u_pageHide(74,true),
    "dstSettings": (c) => u_pageHide(117),
    "importORExportConfiguration": (c) => u_pageHide(42) && c.build_type == "debug",
    "telnetSwitch": (c) => c.account_level == "1" && c.build_type == "debug",
    "modulelogSwitch": (c) => c.account_level == "1",
    "adbSwitch": (c) => c.account_level == "1",
    "sfpIpaSwitch": (c) => u_pageHide(150),
    "commlogBackupSetting": (c) => c.account_level == "1",
    "abnormalAutomaticRestartSwitch": (c) => c.account_level == "1",
    "tr069LogSwitch": (c) => u_pageHide(46),
    "yoctoLogSwitch": (c) => u_pageHide(51) && !c.HIDE_5G,
    "moduleUpdate": (c)=>c.account_level == "1" && !c.HIDE_5G,
    "intelligentrestart": (c) => u_pageHide(117,true),
    "intelligentLightsOut": (c) => u_pageHide(144),
    "ping": (c) => true,
    "tcpdump": (c) => true,
    "trace": (c) => true,
    "remotePacketsCapture": (c) => u_pageHide(43),
}